### ISSUE TITLE
How to calculate areas of grid in Quadrat Statistics?

### ISSUE THREAD

**Issue by hafez-ahmad** [pysal/pointpats#103]
Thank you for developing this excellent package. I have a question regarding the generation of a 3x3 grid based on decimal degree latitude and longitude. Is there a method available to calculate the area of each grid cell?
`q_r = qs.QStatistic(pp_juv,shape= "rectangle",nx = 3, ny = 3)`

Thanks

**Comment by weikang9009** [comment]
Yes. Once you have created an instance of`QStatistic` with your data 
```python
import pointpats.quadrat_statistics as qs
q_r = qs.QStatistic(data,shape= "rectangle",nx = 3, ny = 3)
```
you can use the following code to calculate the area of each grid cell:
```python
q_r.mr.rectangle_width * q_r.mr.rectangle_height
```
