### ISSUE TITLE
argument of type 'builtin_function_or_method' is not iterable

### ISSUE THREAD

**Issue by YTZhou1** [pysal/pointpats#112]
Hi,

we met this error when using the sample data in notebooks/distance_statistics-numpy-oriented.ipynb, thanks!
![image](https://github.com/pysal/pointpats/assets/140090812/5084f1a1-2da4-4114-a233-7a8e80f81afd)

**Comment by martinfleis** [comment]
This is an upstream issue in scikit-learn 1.3.0. It has been fixed on scikit-learn main in the meantime.
