### ISSUE TITLE
release 2.4.0

### ISSUE THREAD

**Issue by martinfleis** [pysal/pointpats#122]
Hey, 

I see that you are actively working on the new stuff (and then [removing](https://github.com/pysal/pointpats/pull/120#issuecomment-1733609631) it) but I wanted to check if it would be okay to cut 2.4.0 this week? I got new Knox and plot_density in my course starting next Tuesday and I'd prefer if students just created an env in the beginning and did not have to touch it (e.g. updating pointpats before we get to point patterns).

Obviously assuming that Know will make it back before the release :)

**Comment by knaaptime** [comment]
Yes. New stuff is ready, just need to add a few doctrines and tests.  Will cut the release in a day or two

**Comment by sjsrey** [comment]
[2.4.0](https://github.com/pysal/pointpats/releases/tag/v2.4.0)
