### ISSUE TITLE
minimum support Python [2024-06]

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pointpats#139]
xref - #136 

Do we want the minimum support Python to the 3.9 or 3.10?

**Comment by jGaboardi** [comment]
If I don't hear from anyone in several hours, I'll go ahead and make a PR for supporting Python 3.10 - 3.12. Easy enough to add back the 3.9 stuff if that's needed.

**Comment by martinfleis** [comment]
We have voted to adopt SPEC0 across the ecosystem, so use whatever that suggests.
