### ISSUE TITLE
(BUG) L function and its Simulation Envelope under the null (CSR) not close to 0

### ISSUE THREAD

**Issue by weikang9009** [pysal/pointpats#44]
This issue is raised by a user of `pointpats` - Wei Xie.

The Simulation Envelope under the null of CSR built for the L function is nowhere near 0 (see the following figure), which is not right based on its definition.
![image](https://user-images.githubusercontent.com/7359284/70667138-061aaa80-1c25-11ea-9b81-af59a80165c0.png)

**Comment by ljwolf** [comment]
I think the [equation is implemented incorrectly.](https://github.com/pysal/pointpats/blob/master/pointpats/distance_statistics.py#L525). It should read:
```python
    support, kestimate = _k(pp, intervals, dmin, dmax, d).T
    lestimate = np.sqrt(kestimate / np.pi)
    return np.column_stack((support, lestimate))
```

This is the form on [wikipeda](https://en.wikipedia.org/wiki/Spatial_descriptive_statistics#Ripley's_K_and_L_functions) and in [`spatstats`](https://github.com/spatstat/spatstat/blob/master/R/Kest.R#L40).

**Comment by jGaboardi** [comment]
FWIW, this is [the formulation](https://github.com/pysal/spaghetti/issues/467#issuecomment-612699306) found in O’Sullivan and Unwin (2010). I was going to add it into `spaghetti` before realizing it is not well-suited for networks.
* **D. O’Sullivan and D. J. Unwin**. *Point Pattern Analysis*, chapter 5, pages 121–156. John Wiley & Sons, Ltd, 2010. doi:10.1002/9780470549094.ch5.

**Comment by weikang9009** [comment]
> spatstats

I do not see a major difference between these two implementations - the only difference is that your implementation does not deducts the distance from the "normalized" L function. The current implementation in `pointpats` follows another routine (as pointed out by @jGaboardi ) and also shown in the Wikipedia:
![image](https://user-images.githubusercontent.com/7359284/80021073-da3ee980-848e-11ea-9f83-51fc99e30168.png)
I think the main purpose is to make the interpretation more intuitive: under the null, the L function follows a horizontal line at 0.

We have found the bug and Serge has fixed it in https://github.com/pysal/pointpats/pull/45/files. Another bug is introduced with this PR and it is supposed to be fixed in https://github.com/pysal/pointpats/pull/46

**Comment by ljwolf** [comment]
I see! Feel free to close this then!

> the only difference...

Right. The plotting correction is not the L function itself. 

I understand the L with this adjustment is interpreted like the J but centered on zero.

I think this needs to be documented + given an option.

**Comment by weikang9009** [comment]
The equation is given in the [example notebook for distance statistics](https://github.com/pysal/pointpats/blob/master/notebooks/distance_statistics.ipynb). I will add the missing equations for the distance functions to the inline docstrings.
