### ISSUE TITLE
Qstatistic.plot does not return axes nor take axes

### ISSUE THREAD

**Issue by ljwolf** [pysal/pointpats#50]
It's challenging to use `QStatistic.plot` alongside `contextily`, since the method 
1. does not allow you to pass an ax 
2. it constructs an axis (in `self.pp.plot()`), rather than requesting an axis using `plt.gca()`
3. it calls `ffigure.show()` rather than returning figure/axis components that can be modified after plotting. 

This means we can't add basemaps, as far as I can tell.

**Comment by ljwolf** [comment]
I think, looking at many of the plotting methods in pointpats, this is a possibility for enhancement. It should be pretty straightforward if we use matplotlib-style returning of figures/axes & taking an `ax` argument.

**Comment by martinfleis** [comment]
Closed by #116
