### ISSUE TITLE
Simulation Envelopes, Low & High

### ISSUE THREAD

**Issue by vpapaioannou** [pysal/pointpats#57]
The way the low and high functions are calculated, https://github.com/pysal/pointpats/blob/master/pointpats/distance_statistics.py#L627, it appears to be confusing since it depends on the `pct` parameter whereas it shouldn't. If `pct=1` then the low and high envelopes are the same as can be seen below.

`realizations = PoissonPointProcess( spp.window, spp.n, 10, asPP = True)`
`kenv = Kenv( spp, intervals = 20, realizations = realizations, pct = 1)`
`kenv.plot()`

![image](https://user-images.githubusercontent.com/6065702/85902296-aefbb200-b7d1-11ea-93b7-a02557b2dfde.png)

If `pct = 0.05` having the same realizations, then,

![image](https://user-images.githubusercontent.com/6065702/85902420-013cd300-b7d2-11ea-9c17-91ea2f563e67.png)

If there is an intention to incorporate some sort of p - value in the graphs, then from what I know this p - value is determined exclusively by the amount realizations and nothing else. Finally, I would suggest to have an assertion about `pct` valid values.

Thanks,

Vasilis

**Comment by sjsrey** [comment]
@vpapaioannou if you could add a PR that illustrates they type of functionality you are interested in, that would be very helpful.

**Comment by vpapaioannou** [comment]
What does PR mean?

To my understanding, the envelopes should be independent from the level of significance. That means, given the existing code, that the low envelope should be always row 0 and the high envelope should be always the last row of numpy array res. They should be the same if only one realization is provided.

**Comment by sjsrey** [comment]
> What does PR mean?
> 

Pull Request

> To my understanding, the envelopes should be independent from the level of significance. That means, given the existing code, that the low envelope should be always row 0 and the high envelope should be always the last row of numpy array res. They should be the same if only one realization is provided.

The simulation envelopes are dependent on the specification of the significance level.

**Comment by vpapaioannou** [comment]
Do you have a reference about "The simulation envelopes are dependent on the specification of the significance level."?

**Comment by sjsrey** [comment]
> Do you have a reference about "The simulation envelopes are dependent on the specification of the significance level."?

https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/13-2042.1

**Comment by vpapaioannou** [comment]
Reading the paper, I understand your rationale. To my mind though, there are two different but very close concepts. The first one is that of the Lower / Upper Bound (LB / UB) and the second one is that of a **K** function at level `\alpha`. In the first case, the LB should be the row 0 in array res, and the UB should be the last row. For the second case, the **K** functions should be reported together with the level `\alpha` so that to be distinguished from the actual LB and UB **K** functions. Also, instead of using the LB / UB labels I would just use K_α.

**Comment by ljwolf** [comment]
Would clarifying the documentation help? It seems your interpretation of *envelope* is the extrema, while we're using it to mean the (1- α)% extrema. It is unlikely that we will change the nomenclature in this code, but a re-vamp of the code is about to [be merged](https://github.com/pysal/pointpats/pull/54) that [is oriented to let users work with simulations directly](https://nbviewer.jupyter.org/github/pysal/pointpats/blob/f8a203627dce57c739c7a072311f693e36d7cd2e/notebooks/distance_statistics-numpy-oriented.ipynb#$K$-function).

**Comment by ljwolf** [comment]
> where the 1 comes from the current point process under testing
I believe this is [done correctly in the new implementation](https://github.com/pysal/pointpats/pull/54/files#diff-b1cd3f52466bb0592f146c31238fb854R586)

**Comment by vpapaioannou** [comment]
Yes, updating the documentation it would be enough. If `pct = 0` then you can get the extrema, otherwise you can get the (1 - α)% extrema.

As of `nres` that I said above, since Python starts from `0`, I think the code is correct. However, if `pct = 0` then an IndexError is raised. Maybe there you need to take care of this in the new implementation.

You are welcome, thanks for implementing all this functionality.

**Comment by ljwolf** [comment]
This should be addressed in the new implementation
