### ISSUE TITLE
poisson point process with delaunay missing first triangle

### ISSUE THREAD

**Issue by giovp** [pysal/pointpats#72]
was looking at the code and found an unexpected behaviour here:

https://github.com/pysal/pointpats/blob/0ca9085fdb082194540568166343b97111993272/pointpats/ripley.py#L129

I'd expect that it should check for `simplex >= 0`.

example:
```python
from pointpats.random import poisson
from scipy.spatial import delaunay_plot_2d, Delaunay, ConvexHull
import numpy as np
import matplotlib.pyplot as plt
rng = np.random.default_rng(10)
points = rng.uniform(0, 10, size=(30, 2))
hull = ConvexHull(points)
vxs = hull.points[hull.vertices]
deln = Delaunay(vxs)

ppp = poisson(hull, size=(100, 1))
fig, ax = plt.subplots(1, 1)
ax.scatter(
    points[..., 0],
    points[..., 1],
    edgecolor="b",
    facecolor="none",
    alpha=0.5,
)
ax.scatter(ppp[:, 0], ppp[:, 1], edgecolor="r", facecolor="none", alpha=0.5)
delaunay_plot_2d(deln)
```

![image](https://user-images.githubusercontent.com/25887487/117338397-ccdc7d80-ae9e-11eb-90a5-f2e1c40b57ac.png)

looks like the first triangle is never covered, cause it is indexed as 0:
```python
deln.find_simplex((2,8))
>>> array(0, dtype=int32)
```

**Comment by ljwolf** [comment]
Yes! that's correct! That should be >= 0.
