### ISSUE TITLE
Cannot import name 'G' from 'pointpats' (/usr/local/lib/python3.7/dist-packages/pointpats/__init__.py)

### ISSUE THREAD

**Issue by Banano19** [pysal/pointpats#78]
Hi, I have an issue. I am working Google Colab and when I try to import 'G' module from 'pointpats' there is an error. I do not have idea why this is happening. Can you help me please?

**Comment by ljwolf** [comment]
Use `g` instead, following [this guide!](https://nbviewer.org/github/pysal/pointpats/blob/master/notebooks/distance_statistics-numpy-oriented.ipynb#Nearest-Neighbor-Distance-Functions) We improved the performance of these functions, but also had to change the API slightly.
