### ISSUE TITLE
pointpats on conda-forge fails pip check

### ISSUE THREAD

**Issue by giswqs** [pysal/pointpats#80]
[Conda-forge](https://github.com/conda-forge/staged-recipes) now recommends adding `pip check` in the recipe. The pointpats package on the conda-forge channel fails `pip check` with an error `pointpats 2.2.0 requires opencv-contrib-python, which is not installed.` This is causing issues for all downstream packages that might be submitted to the conda-forge channel in the future. It appears that `opencv-contrib-python` in the [setup.py](https://github.com/pysal/pointpats/blob/master/setup.py), but it is not available on the conda-forge channel. 

https://github.com/conda-forge/pointpats-feedstock/blob/b433cecfc45129bae5fe956f11f0b7b20efa339d/recipe/meta.yaml#L21

**Comment by giswqs** [comment]
Steps to reproduce the error:
conda install -c conda-forge pointpats
pip check

**Comment by ljwolf** [comment]
Hi @giswqs! The odd thing is that, I think, the package _does not_ require opencv. It's a "soft dependency," being that one function attempts to import it, but if the package is not provided, then the function simply errors. This pattern is used elsehwere in python (such as `pandas.read_excel`) and is pretty common... I will need to read up on how `pip check` works in order to resolve the issue.

**Comment by giswqs** [comment]
The `opencv-contrib-python` package is listed on the [requirements.txt](https://github.com/pysal/pointpats/blob/master/requirements.txt), which is causing the issue. If you remove it from requirements.txt and check the dependency in a module and prompt users to install them if needed, that should solve the issue.

**Comment by giswqs** [comment]
It appears that the only function using opencv is `minimum_rotated_rectangle()`. Since the function already provides error handling, I think `opencv-contrib-python` can be safely removed from requirements.txt. Otherwise, it will cause issues for all pysal downstream packages on conda-forge with `pip check`. Also, `opencv-contrib-python` is quite a large package (150MB). including such a large package as a required dependency that is only used by one function is not ideal. 

https://github.com/pysal/pointpats/blob/9a09bd7ff2c3b5402f02a0a54175193cb643edd8/pointpats/centrography.py#L105-L108

**Comment by martinfleis** [comment]
I believe that this was resolved by #82.
