### ISSUE TITLE
Infrastructure

### ISSUE THREAD

**Issue by martinfleis** [pysal/pointpats#86]
pointpats currently don't have standardised PySAL infrastructure (CI, release action) and I think that the RTD build will also fail because the setup has not been updated to recent versions of sphinx and its extensions. 

Since it looks that geopandas may optionally depend on pointpats, I think this needs to be fixed.

I'll give it a first go but may leave some bits to @jGaboardi.

**Comment by jGaboardi** [comment]
Shall we migrate from `master` to `main` as part of this?

**Comment by martinfleis** [comment]
If you have the rights, go for it.

**Comment by jGaboardi** [comment]
I thumbed up too soon... I don't have any rights.

@sjsrey Can you grant @martinfleis and I the proper permissions here?

**Comment by weikang9009** [comment]
The default branch is main now.

**Comment by martinfleis** [comment]
Can you please remove `master` then?

**Comment by jGaboardi** [comment]
I was able to remove the `master` branch right now. Somehow I have the admin privileges to do that, but not to reassign the default branch. Weird.

**Comment by martinfleis** [comment]
Ah, I was probably able to do that as well. I think that standard branch management (not setting the default) fall under the same category as commit rights.

**Comment by weikang9009** [comment]
The docs are live on https://pysal.org/pointpats/ now.
